name: validation-check

on:
  schedule:
    - cron: '0 8 * * 1-5'   # 17:00 KST (오후 5시)
    - cron: '0 10 * * 1-5'  # 19:00 KST (오후 7시)
  
  # 수동 실행도 가능하게
  workflow_dispatch:

jobs:
  validation-check:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
        
    - name: Install dependencies
      run: |
        pip install pandas python-dotenv slack-sdk selenium

    - name: Install Chrome
      run: |
        sudo apt-get update
        sudo apt-get install -y google-chrome-stable
        
    - name: Run validation check
      env:
        TASKWORLD_EMAIL: ${{ secrets.TASKWORLD_EMAIL }}
        TASKWORLD_PASSWORD: ${{ secrets.TASKWORLD_PASSWORD }}
        SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
        SLACK_CHANNEL: ${{ secrets.SLACK_CHANNEL }}
        SLACK_CHANNEL_VALIDATION: ${{ secrets.SLACK_CHANNEL_VALIDATION }}
      run: |
        python selenium_taskworld_downloader.py validation
        
    - name: Upload logs (if failed)
      if: failure()
      uses: actions/upload-artifact@v4
      with:
        name: validation-error-logs
        path: |
          *.log
